package com.cup.opsagent.planner.llm.provider;

public enum LlmProviderErrorCode {
    LLM_PROVIDER_DISABLED,
    LLM_PROVIDER_MISCONFIGURED,
    LLM_PROVIDER_TIMEOUT,
    LLM_PROVIDER_UNAUTHORIZED,
    LLM_PROVIDER_RATE_LIMITED,
    LLM_PROVIDER_BAD_REQUEST,
    LLM_PROVIDER_SERVER_ERROR,
    LLM_PROVIDER_BAD_RESPONSE,
    LLM_PROVIDER_EMPTY_RESPONSE,
    LLM_PROVIDER_UNSUPPORTED_RESPONSE_FORMAT,
    LLM_PROVIDER_RESPONSE_TOO_LARGE
}
