package com.cup.opsagent.tool.core;

public enum ToolExecutionFailureCode {
    COMMAND_TEMPLATE_ID_MISSING,
    COMMAND_EXECUTION_OPTIONS_MISSING,
    INVALID_COMMAND_TEMPLATE_ARGS,
    COMMAND_SPEC_MISSING,
    SHELL_WRAPPER_DENIED,
    COMMAND_TEMPLATE_MISMATCH,
    PROCESS_START_FAILED,
    COMMAND_TIMEOUT,
    COMMAND_INTERRUPTED
}
