package com.cup.opsagent.rag;

public enum RagProviderErrorCode {
    RAG_PROVIDER_MISCONFIGURED,
    RAG_PROVIDER_UNAUTHORIZED,
    RAG_PROVIDER_TIMEOUT,
    RAG_PROVIDER_RATE_LIMITED,
    RAG_PROVIDER_BAD_REQUEST,
    RAG_PROVIDER_SERVER_ERROR,
    RAG_PROVIDER_BAD_RESPONSE,
    RAG_PROVIDER_UNSUPPORTED
}
