import { useCallback, useState } from 'react'
import { Shield } from 'lucide-react'
import { api, apiErrorMessage } from '../../api/client'
import type { Approval, ApprovalDecision, ApprovalExecution } from '../../api/types'
import { approvals as demoApprovals } from '../../data/demo'
import { useDemoResource } from '../../hooks/useDemoResource'
import { useToast } from '../../hooks/useToast'
import { Toast } from '../../components/ui/Toast'
import { ApprovalCard } from '../../components/safety/ApprovalCard'
import { Badge } from '../../components/ui/Badge'
import { Card } from '../../components/ui/Card'

export default function ApprovalCenterPage() {
  const { data, demo, setData, reload } = useDemoResource(useCallback(() => api.approvals(), []), demoApprovals)
  const [selected, setSelected] = useState<Approval | null>(null); const [lease, setLease] = useState<ApprovalDecision | null>(null); const [execution, setExecution] = useState<ApprovalExecution | null>(null); const { message, show } = useToast()
  const open = async (item: Approval) => { setLease(null); setExecution(null); if (demo) { setSelected(item); return }; try { setSelected(await api.approval(item.approvalId)) } catch (error) { show(apiErrorMessage(error), 'danger') } }
  const decide = async (item: Approval, decision: 'approve' | 'reject') => {
    if (demo) { const status = decision === 'approve' ? 'APPROVED' : 'REJECTED'; const update = { ...item, status }; setData(data.map(value => value.approvalId === item.approvalId ? update : value)); setSelected(update); if (decision === 'approve') setLease({ approvalId: item.approvalId, status, leaseId: `demo-${item.approvalId}`, actionHash: item.actionHash || 'demo', leaseExpiresAt: 'demo only' }); return }
    try { const result = await api.decide(item.approvalId, decision); setLease(result); const detail = await api.approval(item.approvalId); setSelected(detail); setData(data.map(value => value.approvalId === item.approvalId ? detail : value)); show(`Approval ${result.status.toLowerCase()}`) } catch (error) { show(apiErrorMessage(error), 'danger') }
  }
  const execute = async () => { if (!selected || !lease) return; if (demo) { setExecution({ leaseId: lease.leaseId, executionSuccess: true, verified: true, failureCode: 'none', verificationReason: 'Demo execution only' }); setSelected({ ...selected, status: 'CONSUMED' }); return }; try { const result = await api.execute(lease.leaseId, selected.toolName, selected.arguments || {}); setExecution(result); await reload(); setSelected(await api.approval(selected.approvalId)); show(result.executionSuccess && result.verified ? 'Operation executed and verified' : 'Operation completed but verification failed', result.executionSuccess && result.verified ? 'success' : 'danger') } catch (error) { show(apiErrorMessage(error), 'danger') } }
  const pending = data.filter(item => item.status === 'PENDING'); const critical = pending.filter(item => item.riskLevel === 'CRITICAL' || item.riskLevel === 'HIGH')
  return <div className="page"><div className="pagehead"><div><p>HUMAN-IN-THE-LOOP CONTROL</p><h1>Approval center</h1></div><Badge tone="demo">{demo ? 'DEMO QUEUE' : 'LIVE QUEUE'}</Badge></div><div className="approval-banner"><Shield/><div><b>{pending.length} operations await trusted authorization</b><span>Approval creates a short-lived lease bound to the approved action hash.</span></div><Badge tone="danger">{critical.length} HIGH+</Badge></div><Card><div className="table-head"><div><p>APPROVAL QUEUE</p><h3>Risk-aware operations</h3></div></div><div className="approval-list">{data.map(item => <ApprovalCard approval={item} onDecide={decide} onOpen={open} key={item.approvalId}/>)}</div></Card>{selected && <div className="modal-backdrop" role="presentation"><Card className="approval-detail"><div className="cardhead"><h3>Approval detail</h3><button className="ghost" onClick={() => setSelected(null)}>Close</button></div><dl>{[['approvalId',selected.approvalId],['traceId',selected.traceId],['requester',selected.requester],['toolName',selected.toolName],['serviceName',selected.serviceName],['arguments',JSON.stringify(selected.arguments || {}, null, 2)],['riskLevel',selected.riskLevel],['reason',selected.reason],['status',selected.status],['actionHash',selected.actionHash],['createdAt',selected.createdAt],['expiresAt',selected.expiresAt],['decidedAt',selected.decidedAt],['decidedBy',selected.decidedBy]].map(([key,value]) => <div key={key}><dt>{key}</dt><dd><code>{value || '—'}</code></dd></div>)}</dl>{lease && <p>Lease: <code>{lease.leaseId}</code> · Hash: <code>{lease.actionHash}</code> · Expires: {lease.leaseExpiresAt}</p>}{selected.status === 'PENDING' && <div className="actions"><button className="approve" onClick={() => decide(selected, 'approve')}>Approve</button><button className="reject" onClick={() => decide(selected, 'reject')}>Reject</button></div>}{selected.status === 'APPROVED' && lease && <button className="primary" onClick={execute}>Execute approved operation</button>}{execution && <p>Execution: {String(execution.executionSuccess)} · Verified: {String(execution.verified)} · Failure: {execution.failureCode} · {execution.verificationReason}</p>}</Card></div>}<Toast message={message}/></div>
}
