create table approval_records (
    approval_id varchar(64) primary key,
    trace_id varchar(64) not null,
    step_id varchar(128) not null,
    requester_id varchar(128) not null,
    tool_name varchar(128) not null,
    canonical_arguments text not null,
    risk_level varchar(32) not null,
    action_hash varchar(128) not null,
    status varchar(32) not null,
    reason text not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    decided_at timestamp with time zone,
    decided_by varchar(128) not null
);

create index idx_approval_records_trace_id on approval_records(trace_id);
create index idx_approval_records_status on approval_records(status);

create table execution_leases (
    lease_id varchar(64) primary key,
    approval_id varchar(64) not null,
    action_hash varchar(128) not null,
    tool_name varchar(128) not null,
    canonical_arguments text not null,
    issued_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    constraint fk_execution_leases_approval foreign key (approval_id) references approval_records(approval_id)
);

create index idx_execution_leases_approval_id on execution_leases(approval_id);

create table audit_traces (
    trace_id varchar(64) primary key,
    user_input text not null,
    started_at timestamp with time zone not null,
    ended_at timestamp with time zone,
    status varchar(64) not null,
    final_answer text
);

create table audit_events (
    event_id bigint generated by default as identity primary key,
    trace_id varchar(64) not null,
    event_type varchar(64) not null,
    event_time timestamp with time zone not null,
    success boolean not null,
    payload text not null,
    error_message text,
    previous_hash varchar(128) not null,
    event_hash varchar(128) not null,
    constraint fk_audit_events_trace foreign key (trace_id) references audit_traces(trace_id)
);

create index idx_audit_events_trace_id on audit_events(trace_id);
create index idx_audit_events_event_time on audit_events(event_time);
